### ISSUE TITLE
mshow: inconsistent enumeration of MIME parts

### ISSUE THREAD

**Issue by algor512** [leahneukirchen/mblaze#255] opened 2023-12-20 11:19 UTC
The numbering of MIME parts differs in `mshow` and `mshow -t`, for example, `mshow` shows
```
From: <...>
Subject: Test
To: <...>
Date: Tue, 19 Dec 2023 17:45:46 +0100 (CET) (18 hours, 28 minutes, 29 seconds ago)

--- 1: multipart/mixed size=3224058 ---
--- --- 2: multipart/alternative size=451 ---
--- --- --- 3: text/plain size=13 ---
Test email.
--- --- 4: image/jpeg size=2175349 name="img.jpg" ---
no filter or default handler
--- --- 5: application/pdf size=210485 name="doc.pdf" ---
no filter or default handler 
```
while `mshow -t` shows
```
<path to file>
  1: multipart/mixed size=3224058
    2: multipart/alternative size=451
      3: text/plain size=13
      4: text/html size=166
    5: image/jpeg size=2175349 name="img.jpg"
    6: application/pdf size=210485 name="doc.pdf"
```

**Comment by leahneukirchen** [comment] 2023-12-20 13:48
Duplicate of https://github.com/leahneukirchen/mblaze/issues/247

This is not so easy to fix without additional work :(

**Closed by leahneukirchen** 2023-12-20 13:48 UTC
